# servers:
#   - url: http://localhost:3000
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
# security:
#   - bearerAuth: []
paths:
  /api/auth/signup:
    post:
      tags:
        - default
      summary: Register a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Muritala David
                email: davmuri1414@gmail.com
                password: Famzer22@
                img: ok
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/verify:
    post:
      tags:
        - default
      summary: Verify A User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                token: >-
                  8aff3e468636878d22163d5122c38b87125bff813ec2d846a83f9cf03498d7a7
                id: 4
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/request-email-verification:
    post:
      tags:
        - default
      summary: Request Email Verification
      requestBody:
        content: {}
      parameters:
        - name: email
          in: query
          schema:
            type: string
          example: davmuri1414@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/request-password-reset:
    post:
      tags:
        - default
      summary: Request Reset Password
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: email
          in: query
          schema:
            type: string
          example: davmuri1414@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users:
    put:
      tags:
        - default
      summary: Update A User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Bode Thomas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/login:
    post:
      tags:
        - default
      summary: Login a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: davmuri1414@gmail.com
                password: Famzer22@
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/reset-password:
    post:
      tags:
        - default
      summary: Reset Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userId: 1
                resetToken: >-
                  2db3c6ef4e116445ace1d8a5c582bd3098e4fc5a64b7bff33a47098a713908fa
                password: passerBy22@
                passwordConfirm: passerBy22@
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/posts/create:
    post:
      tags:
        - default
      summary: Create a post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                authorId: 4
                title: Example
                content: A content
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/posts/publish/1:
    put:
      tags:
        - default
      summary: Publish Post
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/posts/1:
    get:
      tags:
        - default
      summary: Get Post By Id
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/posts:
    get:
      tags:
        - default
      summary: Get all posts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}